"""add_document_ingestion_status_and_chunks

Revision ID: 9f2c8a9489a0
Revises: e1e4101c478b
Create Date: 2026-03-12 15:04:30.707914

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9f2c8a9489a0"
down_revision: str | Sequence[str] | None = "e1e4101c478b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("chunk_text", sa.String(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "chunk_index", name="uq_doc_chunk_idx"),
    )
    op.create_index(
        op.f("ix_document_chunks_document_id"), "document_chunks", ["document_id"], unique=False
    )
    op.create_index(op.f("ix_document_chunks_id"), "document_chunks", ["id"], unique=False)
    op.add_column(
        "documents",
        sa.Column(
            "ingestion_status", sa.String(length=30), server_default="queued", nullable=False
        ),
    )
    op.add_column("documents", sa.Column("ingestion_error", sa.String(length=3000), nullable=True))
    op.add_column(
        "documents", sa.Column("ingestion_started_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "documents", sa.Column("ingestion_completed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("documents", sa.Column("content_hash", sa.String(length=128), nullable=True))
    op.add_column(
        "documents", sa.Column("chunk_count", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column("documents", sa.Column("embedding_model", sa.String(length=120), nullable=True))
    op.add_column("documents", sa.Column("embedding_version", sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "embedding_version")
    op.drop_column("documents", "embedding_model")
    op.drop_column("documents", "chunk_count")
    op.drop_column("documents", "content_hash")
    op.drop_column("documents", "ingestion_completed_at")
    op.drop_column("documents", "ingestion_started_at")
    op.drop_column("documents", "ingestion_error")
    op.drop_column("documents", "ingestion_status")
    op.drop_index(op.f("ix_document_chunks_id"), table_name="document_chunks")
    op.drop_index(op.f("ix_document_chunks_document_id"), table_name="document_chunks")
    op.drop_table("document_chunks")
    # ### end Alembic commands ###
