"""add document file metadata fields

Revision ID: e1e4101c478b
Revises: e221f3d11b21
Create Date: 2026-03-12 12:59:02.677777

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e1e4101c478b"
down_revision: str | Sequence[str] | None = "e221f3d11b21"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("file_name", sa.String(length=255), nullable=False))
    op.add_column("documents", sa.Column("file_path", sa.String(length=1000), nullable=False))
    op.add_column("documents", sa.Column("file_size_bytes", sa.Integer(), nullable=True))
    op.add_column("documents", sa.Column("mime_type", sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "mime_type")
    op.drop_column("documents", "file_size_bytes")
    op.drop_column("documents", "file_path")
    op.drop_column("documents", "file_name")
    # ### end Alembic commands ###
